/*var books = ["COMPENDIUM ON OSHO DYNAMIC MEDITATION",
"MEDITATION:ART OF ECSTACY",
"MEDITATION:FIRST AND LAST FREEDOM",
"OSHO MEDITATION INC",
"NEW ALCHEMY TO TURN YOU ON",
"THE PERFECT WAY",
"AND NOW AND HERE",
"ASTROLOGY",
"BREAKING ALL BOUNDRIES",
"DIMENTION BEYOND THE KNOWN",
"ETERNAL QUEST",
"FALLING ON LOVE WITH DARKNESS",
"FROM SEX TO SUPECONSCIOUSNESS",
"HIDDEN MYSTRIES",
"INDEPENDENT MIND",
"INSEARCH OF MIRACULOUS",
"INTO THE VOID",
"KEYS TO A NEW LIFE",
"PSYCHOLOGY OF THE ESOTERIC",
"RELIGIONS EXPIRATION DATE",
"SEARCH FOR PEACE",
"SILENCE THE MESSAGE OF YOUR BEING",
"THREE STEPS TO AWAKENING",
"CUP OF TEA",
"EARTHEN LAMPS",
"FLOWERS OF LOVE",
"LIFE IS A SOAP BUBBLE",
"LOVE LETTERS TO LIFE",
"RANDOM THOUGHTS",
"BOOKS I HAVE LOVED",
"GLIMPSES OF A GOLDEN CHILDHOOD",
"NOTES OF A MAD MAN",
"ABOVE ALL DON'T WOBBLE",
"HAMMER ON THE ROCK",
"BEYOND ENLIGHTENMENT",
"BEYOND PSYCHOLOGY",
"COME", "COME", "YET AGAIN COME",
"FROM UNCONSCIOUSNESS TO CONSCIOUSNESS",
"GOOSE IS OUT",
"MY WAY: WAY OF THE WHITE CLOUDS",
"PATH OF MYSTIC",
"REBLLIOUS SPIRIT",
"THE WILD GEESE AND THE WATER",
"BOOK OF SECRETS",
"TANTRA EXPERIENCE",
"TANTRIC TRANSFORMATION",
"EMPTY BOAT  ",
"HSIN HSIN MING: THE BOOK OF NOTHING",
"SECRET OF SECRETS  ",
"SEARCH",
"WORK IS LOVE MADE VISIBLE",
"PATH OF YOGA ( VOL 1 )",
"HEART OF YOGA (VOL.2)",
"YOGA MYSTERY BEYOND MIND ( VOL 3 )",
"ALCHEMY OF YOGA (VOL.4)",
"YOGA : A NEW DIRECTION (VOL. 5)",
"BODHIDHARMA:THE GREATEST ZEN MASTER(HB)",
"DANCING IN THE BREEZE",
"FINDING YOUR OWN WAY",
"LEARNING HAPPINESS",
"HEART SUTRA",
"ISAN NO FOOTPRINTS IN THE BLUE SKY",
"JOSHU THE LION'S ROAR: ZEN",
"MA TZU THE EMPTY MIRROR",
"AH", "THIS",
"AND THE FLOWERS SHOWERED",
"AND THE GRASS GROWS BY ITASELF",
"TAKE IT EASY",
"YAA-HOO THE MYSTIC ROSE",
"ZEN MANIFESTO",
"ZEN: THE QUANTUM LEAP FROM MIND TO NO -MIND    ",
"I SAY UNTO YOU VOL 1",
"GUIDA SPIRITUALE",
"THE HIDDEN",
"PHILOSOPHIA PERENNIS VOL 01",
"PHILOSOPHIA PERENNIS VOL 02",
"REFLECTIONS ON KAHLIL GIBRANS THE PROPHET",
"ZARATHUSTRA:GOD THAT CAN DANCE",
"ZARATHUSTRA:LAUGHING PROPHET",
"AS IF A TREE STARTS RUNNING",
"THE DIVINE MELODY",
"PHILOSOPHIA ULTIMA",
"PATH OF LOVE",
"VEDANTA :SEVEN STEPS TO SAMADHI",
"TAKE IT EASY",
"YAA-HOO THE MYSTIC ROSE",
"ZEN MANIFESTO",
"ZEN: THE QUANTUM LEAP FROM MIND TO NO -MIND    ",
"I SAY UNTO YOU VOL 1",
"GUIDA SPIRITUALE",
"THE HIDDEN",
"PHILOSOPHIA PERENNIS VOL 01",
"PHILOSOPHIA PERENNIS VOL 02",
"REFLECTIONS ON KAHLIL GIBRANS THE PROPHET",
"ZARATHUSTRA:GOD THAT CAN DANCE",
"ZARATHUSTRA:LAUGHING PROPHET",
"AS IF A TREE STARTS RUNNING",
"THE DIVINE MELODY",
"PHILOSOPHIA ULTIMA",
"PATH OF LOVE",
"VEDANTA :SEVEN STEPS TO SAMADHI",
"WAY BEYOND ANY WAY"
]; */

// <!-- <div class="book-name">
//              <img src="" alt="">
//            <p class="discount"></p>
//          <h2></h2>
//        <div class="book-prize">
//          <p></p>
//        <p></p>
//  </div>
//<a href="#">Buy Now</a>
//</div> -->








/*var i = 0;

while (i < books.length) {
    var content = document.getElementById("myUL");
    var bookName = document.createElement("div");
    bookName.setAttribute("class", "book-name");
    content.appendChild(bookName);
    if (i === 0) {
        var image = document.createElement("img");
        bookNameSelect = document.querySelector(".book-name");
        bookNameSelect.appendChild(image);
        var discount = document.createElement("p");
        discount.setAttribute("class", "discount");
        bookNameSelect.appendChild(discount);
        var bookHead = document.createElement("h3");
        bookHead.setAttribute("id", "booktitle");

        bookNameSelect.appendChild(bookHead);
        var bookPrize = document.createElement("div");
        bookPrize.setAttribute("class", "book-prize");
        bookNameSelect.appendChild(bookPrize);
        bookPrizeSelect = document.querySelector(".book-prize");
        var p1 = document.createElement("p");
        p1.setAttribute("class", "mrp");
        var p2 = document.createElement("p");
        p2.setAttribute("class", "sell-prize");
        var p3 = document.createElement("p");
        p3.setAttribute("class", "shipping");
        bookPrizeSelect.appendChild(p1);
        bookPrizeSelect.appendChild(p2);
        bookPrizeSelect.appendChild(p3);
        var link = document.createElement("a");
        link.setAttribute("href", "#");
        bookNameSelect.appendChild(link);
    }
    i++;
} */


let btnGet = document.querySelector('.btnList');
let myTable = document.querySelector('#table');

let employees = [
{"SR. NO.":"1","HINDI BOOKS TITLE NAME":"KRISHNA SMRITI","SUBJECT":"KRISHNA","COVER":"HB","(MRP)":"1000"},
{"SR. NO.":"2","HINDI BOOKS TITLE NAME":"JYON KI TYON DHAR DEENHI CHADARIYA","SUBJECT":"MAHAVEER","COVER":"HB","(MRP)":"660"},
{"SR. NO.":"3","HINDI BOOKS TITLE NAME":"JIN SUTRA VOL 1","SUBJECT":"MAHAVEER","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"4","HINDI BOOKS TITLE NAME":"JIN SUTRA VOL 2","SUBJECT":"MAHAVEER","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"5","HINDI BOOKS TITLE NAME":"JIN SUTRA VOL 3","SUBJECT":"MAHAVEER","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"6","HINDI BOOKS TITLE NAME":"JIN SUTRA VOL 4","SUBJECT":"MAHAVEER","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"7","HINDI BOOKS TITLE NAME":"MARO HE JOGI MARO","SUBJECT":"GORAKH","COVER":"HB","(MRP)":"960"},
{"SR. NO.":"8","HINDI BOOKS TITLE NAME":"NAHIN SANJH NAHIN BHOR","SUBJECT":"CHARANDAS","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"9","HINDI BOOKS TITLE NAME":"SHIV SUTRA","SUBJECT":"SHIV","COVER":"HB","(MRP)":"720"},
{"SR. NO.":"10","HINDI BOOKS TITLE NAME":"SAHAJ YOG","SUBJECT":"SARHAPA","COVER":"HB","(MRP)":"700"},
{"SR. NO.":"11","HINDI BOOKS TITLE NAME":"EK OMKAR SATNAM","SUBJECT":"NANAK","COVER":"HB","(MRP)":"860"},
{"SR. NO.":"12","HINDI BOOKS TITLE NAME":"KAHE HOT ADHEER","SUBJECT":"PALTUVANI","COVER":"HB","(MRP)":"560"},
{"SR. NO.":"13","HINDI BOOKS TITLE NAME":"MAN HI POOJA MAN HI DHOOP","SUBJECT":"RAIDAS","COVER":"HB","(MRP)":"740"},
{"SR. NO.":"14","HINDI BOOKS TITLE NAME":"DARIYA KAHAI SABAD NIRBANA","SUBJECT":"DARIYADAS","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"15","HINDI BOOKS TITLE NAME":"AKATH KAHANI PREM KI","SUBJECT":"PHARID","COVER":"HB","(MRP)":"660"},
{"SR. NO.":"16","HINDI BOOKS TITLE NAME":"KASTURI KUNDAL BASAI","SUBJECT":"KABIR","COVER":"HB","(MRP)":"520"},
{"SR. NO.":"17","HINDI BOOKS TITLE NAME":"SUNO BHAI SADHO","SUBJECT":"KABIR","COVER":"HB","(MRP)":"540"},
{"SR. NO.":"18","HINDI BOOKS TITLE NAME":"MERA MUJHMEIN KUCHH NAHIN","SUBJECT":"KABIR","COVER":"HB","(MRP)":"700"},
{"SR. NO.":"19","HINDI BOOKS TITLE NAME":"UPASNA KE KSHAN","SUBJECT":"ANTARANG","COVER":"HB","(MRP)":"0"},
{"SR. NO.":"20","HINDI BOOKS TITLE NAME":"ASAMBHAV KRANTI","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"440"},
{"SR. NO.":"21","HINDI BOOKS TITLE NAME":"DHYAN SUTRA","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"400"},
{"SR. NO.":"22","HINDI BOOKS TITLE NAME":"APNE MAHI TATOL","SUBJECT":"DHYAN/SADHANA","COVER":"PB","(MRP)":"300"},
{"SR. NO.":"23","HINDI BOOKS TITLE NAME":"DHYANYOG:PRATHAM AUR ANTIN MUKTI","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"520"},
{"SR. NO.":"24","HINDI BOOKS TITLE NAME":"JIN KHOJA TIN PAIYA","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"1060"},
{"SR. NO.":"25","HINDI BOOKS TITLE NAME":"MAIN MRITU SIKHATA HUN","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"1000"},
{"SR. NO.":"26","HINDI BOOKS TITLE NAME":"MAIN KAUN HUN ?","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"460"},
{"SR. NO.":"27","HINDI BOOKS TITLE NAME":"SADHANA PATH","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"1000"},
{"SR. NO.":"28","HINDI BOOKS TITLE NAME":"JEEVAN HI HAI PRABHU","SUBJECT":"DHYAN/SADHANA","COVER":"PB","(MRP)":"320"},
{"SR. NO.":"29","HINDI BOOKS TITLE NAME":"JEEVAN SANGEET","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"420"},
{"SR. NO.":"30","HINDI BOOKS TITLE NAME":"MAIN KAHTA ANKHAN DEKHI ( OMI )","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"360"},
{"SR. NO.":"31","HINDI BOOKS TITLE NAME":"SAMADHI KE SAPT DWAR","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"920"},
{"SR. NO.":"32","HINDI BOOKS TITLE NAME":"SATYA KI KHOJ","SUBJECT":"DHYAN/SADHANA","COVER":"PB","(MRP)":"260"},
{"SR. NO.":"33","HINDI BOOKS TITLE NAME":"SAMBHAVNAON KI AHAT","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"360"},
{"SR. NO.":"34","HINDI BOOKS TITLE NAME":"KATHOPANISHAD","SUBJECT":"UPANISHAD","COVER":"HB","(MRP)":"1000"},
{"SR. NO.":"35","HINDI BOOKS TITLE NAME":"JEEVAN GEET","SUBJECT":"PRASHNOTTAR","COVER":"PB","(MRP)":"200"},
{"SR. NO.":"36","HINDI BOOKS TITLE NAME":"DHYAN DARSHAN","SUBJECT":"DHYAN/SADHANA","COVER":"HB","(MRP)":"320"},
{"SR. NO.":"37","HINDI BOOKS TITLE NAME":"SADHANA SUTRA","SUBJECT":"MAIBEEL COLLINS","COVER":"HB","(MRP)":"860"},
{"SR. NO.":"38","HINDI BOOKS TITLE NAME":"KRANTIBEEJ","SUBJECT":"PATRA-SANKALAN","COVER":"HB","(MRP)":"540"},
{"SR. NO.":"39","HINDI BOOKS TITLE NAME":"YOG NAYE AYAM","SUBJECT":"YOG","COVER":"PB","(MRP)":"220"},
{"SR. NO.":"40","HINDI BOOKS TITLE NAME":"JHUK AYEE BADARIYA SAWAN KI","SUBJECT":"MEERA","COVER":"HB","(MRP)":"780"},
{"SR. NO.":"41","HINDI BOOKS TITLE NAME":"ANANT KI PUKAR","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"400"},
{"SR. NO.":"42","HINDI BOOKS TITLE NAME":"SHUNYA KE PAAR","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"43","HINDI BOOKS TITLE NAME":"JEEVAN RAHASYA","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"420"},
{"SR. NO.":"44","HINDI BOOKS TITLE NAME":"SAMBHOG SE SAMADHI KI AUR","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"680"},
{"SR. NO.":"45","HINDI BOOKS TITLE NAME":"SATYA KA DARSHAN","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"320"},
{"SR. NO.":"46","HINDI BOOKS TITLE NAME":"VIGYAN DHARAM AUR KALA","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"440"},
{"SR. NO.":"47","HINDI BOOKS TITLE NAME":"MAIN DHARMIKTA SIKHATA HUN..","SUBJECT":"VIVIDH","COVER":"","(MRP)":"0"},
{"SR. NO.":"48","HINDI BOOKS TITLE NAME":"KYA MANUSHYA EK YANTRA HAI?","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"280"},
{"SR. NO.":"49","HINDI BOOKS TITLE NAME":"JYOTISH VIGYAN","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"280"},
{"SR. NO.":"50","HINDI BOOKS TITLE NAME":"PANTH PREM KO ATPATO","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"240"},
{"SR. NO.":"51","HINDI BOOKS TITLE NAME":"PATH KI KHOJ","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"400"},
{"SR. NO.":"52","HINDI BOOKS TITLE NAME":"KARUNA AUR KRANTI","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"300"},
{"SR. NO.":"53","HINDI BOOKS TITLE NAME":"SWAYAM KI SATTA","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"340"},
{"SR. NO.":"54","HINDI BOOKS TITLE NAME":"PHIR AMRIT KI BUND PARI","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"220"},
{"SR. NO.":"55","HINDI BOOKS TITLE NAME":"AMRIT DWAR","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"260"},
{"SR. NO.":"56","HINDI BOOKS TITLE NAME":"ANKHO DEKHI SANCH","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"320"},
{"SR. NO.":"57","HINDI BOOKS TITLE NAME":"JEEVAN DARSHAN","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"340"},
{"SR. NO.":"58","HINDI BOOKS TITLE NAME":"JEEVAN KRANTI KE SUTRA","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"320"},
{"SR. NO.":"59","HINDI BOOKS TITLE NAME":"EK NAYA DWAR","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"280"},
{"SR. NO.":"60","HINDI BOOKS TITLE NAME":"JEEVAN KI KHOJ","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"320"},
{"SR. NO.":"61","HINDI BOOKS TITLE NAME":"GAHRE PANI PAITH","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"340"},
{"SR. NO.":"62","HINDI BOOKS TITLE NAME":"KYA ISHWAR MAR GAYA HAI?","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"300"},
{"SR. NO.":"63","HINDI BOOKS TITLE NAME":"TAMSO MA JYOTIRGAMAY","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"480"},
{"SR. NO.":"64","HINDI BOOKS TITLE NAME":"SATYA KI PYAS","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"400"},
{"SR. NO.":"65","HINDI BOOKS TITLE NAME":"CHETI SAKE TO CHET","SUBJECT":"VIVIDH","COVER":"PB","(MRP)":"360"},
{"SR. NO.":"66","HINDI BOOKS TITLE NAME":"MAN KA DARPAN","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"300"},
{"SR. NO.":"67","HINDI BOOKS TITLE NAME":"AMRIT VARSHA","SUBJECT":"VIVIDH","COVER":"HB","(MRP)":"380"},
{"SR. NO.":"68","HINDI BOOKS TITLE NAME":"MITTI KE DIYE","SUBJECT":"BODH KATHA","COVER":"HB","(MRP)":"420"},
{"SR. NO.":"69","HINDI BOOKS TITLE NAME":"DHYAN KE KAMAL","SUBJECT":"SADHANA SHIVIR","COVER":"HB","(MRP)":"300"},
{"SR. NO.":"70","HINDI BOOKS TITLE NAME":"SHUNYA KI NAV","SUBJECT":"DHYAN/SADHANA","COVER":"","(MRP)":"0"},
{"SR. NO.":"71","HINDI BOOKS TITLE NAME":"BIN BATI BIN TEL","SUBJECT":"UPANISHAD","COVER":"HB","(MRP)":"1000"},
{"SR. NO.":"72","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 01","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"73","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 02","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"0"},
{"SR. NO.":"74","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 03","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"75","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 04","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"76","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 05","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"77","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 06","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"78","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 07","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"79","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 08","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"80","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 09","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"81","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 10","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"82","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 11","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"83","HINDI BOOKS TITLE NAME":"ES DHAMMO SANANTANO VOL 12","SUBJECT":"BUDHHA","COVER":"HB","(MRP)":"760"},
{"SR. NO.":"84","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 1","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"85","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 2","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"86","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 3","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"87","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 4","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"88","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 5","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"89","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 6","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"90","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 7","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"91","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 8","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"92","HINDI BOOKS TITLE NAME":"ASHTAVAKRA MAHAGITA VOL 9","SUBJECT":"ASHTAVAKRA","COVER":"HB","(MRP)":"800"},
{"SR. NO.":"93","HINDI BOOKS TITLE NAME":"Athato Bhakti Jinghysa Vol.01","SUBJECT":"Shandilya","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"94","HINDI BOOKS TITLE NAME":"Athato Bhakti Jinghysa Vol.02","SUBJECT":"Shandilya","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"95","HINDI BOOKS TITLE NAME":"Bhakti Sutra","SUBJECT":"Narad","COVER":"HB","(MRP)":"0"},
{"SR. NO.":"96","HINDI BOOKS TITLE NAME":"Bharat Ek Amrit Path","SUBJECT":"null","COVER":"HB","(MRP)":"595"},
{"SR. NO.":"97","HINDI BOOKS TITLE NAME":"Bharat Ke Jalte Prashna","SUBJECT":"Rajneeti & Shiksha","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"98","HINDI BOOKS TITLE NAME":"Diya Tale Andhera","SUBJECT":"Kahaniya","COVER":"HB","(MRP)":"0"},
{"SR. NO.":"99","HINDI BOOKS TITLE NAME":"Hasiba Khelia Dhariba Dhyanam","SUBJECT":"null","COVER":"PB","(MRP)":"125"},
{"SR. NO.":"100","HINDI BOOKS TITLE NAME":"Mahaveer Vani Vol.01","SUBJECT":"Mahaveer","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"101","HINDI BOOKS TITLE NAME":"Mahaveer Vani Vol.02","SUBJECT":"Mahaveer","COVER":"HB","(MRP)":"600"},
{"SR. NO.":"102","HINDI BOOKS TITLE NAME":"Nahi Ram Bin Tao","SUBJECT":"Prashnottar","COVER":"HB","(MRP)":"350"},
{"SR. NO.":"103","HINDI BOOKS TITLE NAME":"Patanjali Yog Sutra Vol.1","SUBJECT":"Yog","COVER":"HB","(MRP)":"450"},
{"SR. NO.":"104","HINDI BOOKS TITLE NAME":"Patanjali Yog Sutra Vol.2","SUBJECT":"Yog","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"105","HINDI BOOKS TITLE NAME":"Patanjali Yog Sutra Vol.3","SUBJECT":"Yog","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"106","HINDI BOOKS TITLE NAME":"Patanjali Yog Sutra Vol.4","SUBJECT":"Yog","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"107","HINDI BOOKS TITLE NAME":"Patanjali Yog Sutra Vol.5","SUBJECT":"Yog","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"108","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 1","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"109","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 2","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"110","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 3","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"111","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 4","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"112","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 5","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"113","HINDI BOOKS TITLE NAME":"Tao Upnishad Vol. 6","SUBJECT":"Tao","COVER":"HB","(MRP)":"500"},
{"SR. NO.":"114","HINDI BOOKS TITLE NAME":"Antaryatra ke Path Par","SUBJECT":"Sufi","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"115","HINDI BOOKS TITLE NAME":"Bahuri Na Aiso Davn","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"116","HINDI BOOKS TITLE NAME":"Ishavasyopanishad","SUBJECT":"Upanishad","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"117","HINDI BOOKS TITLE NAME":"Jo Bolen to Hari Katha","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"118","HINDI BOOKS TITLE NAME":"Tantra Sutra Vol 1","SUBJECT":"Tantra","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"119","HINDI BOOKS TITLE NAME":"Tantra Sutra Vol. 2","SUBJECT":"Tantra","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"120","HINDI BOOKS TITLE NAME":"Tantra Sutra Vol.3","SUBJECT":"Tantra","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"121","HINDI BOOKS TITLE NAME":"Tantra Sutra Vol.4","SUBJECT":"Tantra","COVER":"PB","(MRP)":"250"},
{"SR. NO.":"122","HINDI BOOKS TITLE NAME":"Tantra sutra Vol.5","SUBJECT":"Tantra","COVER":"PB","(MRP)":"275"},
{"SR. NO.":"123","HINDI BOOKS TITLE NAME":"Us Path Ke Pathik","SUBJECT":"Sufi","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"124","HINDI BOOKS TITLE NAME":"Vyasta Jeevan Mein Ishwar Ki Khoj (H)","SUBJECT":"Vividh","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"125","HINDI BOOKS TITLE NAME":"Bin Ghan Parat Phuhar (PB)","SUBJECT":"Sahajobai","COVER":"PB","(MRP)":"200"},
{"SR. NO.":"126","HINDI BOOKS TITLE NAME":"Jo Ghar Bhare Apna","SUBJECT":"Vividh","COVER":"PB","(MRP)":"0"},
{"SR. NO.":"127","HINDI BOOKS TITLE NAME":"Lagan Muhurat Jhoot Sab","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"150"},
{"SR. NO.":"128","HINDI BOOKS TITLE NAME":"Prem Kya Hai","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"200"},
{"SR. NO.":"129","HINDI BOOKS TITLE NAME":"Ami Jharat Bigsat Kanwal","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"225"},
{"SR. NO.":"130","HINDI BOOKS TITLE NAME":"Ram Nam Jano Nahi","SUBJECT":"Prashnottar","COVER":"PB","(MRP)":"195"},
{"SR. NO.":"131","HINDI BOOKS TITLE NAME":"Samund Samana Bund Mein","SUBJECT":"Vividh","COVER":"PB","(MRP)":"125"},
{"SR. NO.":"132","HINDI BOOKS TITLE NAME":"Sansar Aur Marg","SUBJECT":"Tao","COVER":"PB","(MRP)":"150"}
]

let headers = ['SR. NO.', 'HINDI BOOKS TITLE NAME', 'SUBJECT', 'COVER', '(MRP)'];
 
btnGet.addEventListener('click', () => {
    let table = document.createElement('table');
    let headerRow = document.createElement('tr');
 
    headers.forEach(headerText => {
        let header = document.createElement('th');
        let textNode = document.createTextNode(headerText);
        header.appendChild(textNode);
        headerRow.appendChild(header);
    });
 
    table.appendChild(headerRow);
 
    employees.forEach(emp => {
        let row = document.createElement('tr');
 
        Object.values(emp).forEach(text => {
            let cell = document.createElement('td');
            let textNode = document.createTextNode(text);
            cell.appendChild(textNode);
            row.appendChild(cell);
        })
 
        table.appendChild(row);
    });
 
    myTable.appendChild(table);
});