// hindi books name

var books = ["KRISHNA SMRITI", "JYON KI TYON DHAR DEENHI CHADARIYA", "JIN SUTRA VOL 1", "JIN SUTRA VOL 2", "JIN SUTRA VOL 3", "JIN SUTRA VOL 4", "MARO HE JOGI MARO", "NAHIN SANJH NAHIN BHOR", "SHIV SUTRA", "SAHAJ YOG", "EK OMKAR SATNAM", "KAHE HOT ADHEER", "MAN HI POOJA MAN HI DHOOP ", "DARIYA KAHAI SABAD NIRBANA ", "AKATH KAHANI PREM KI ", "KASTURI KUNDAL BASAI",
"SUNO BHAI SADHO",
"MERA MUJHMEIN KUCHH NAHIN",
"ASAMBHAV KRANTI",
"DHYAN SUTRA",
"APNE MAHI TATOL",
"DHYANYOG:PRATHAM AUR ANTIN MUKTI",
"JIN KHOJA TIN PAIYA",
"MAIN MRITU SIKHATA HUN",
"MAIN KAUN HUN ?",
"SADHANA PATH",
"JEEVAN HI HAI PRABHU",
"JEEVAN SANGEET",
"MAIN KAHTA ANKHAN DEKHI ( OMI )",
"SAMADHI KE SAPT DWAR",
"SATYA KI KHOJ",
"SAMBHAVNAON KI AHAT",
"KATHOPANISHAD",
"JEEVAN GEET",
"DHYAN DARSHAN",
"SADHANA SUTRA",
"KRANTIBEEJ",
"YOG NAYE AYAM",
"JHUK AYEE BADARIYA SAWAN KI",
"ANANT KI PUKAR",
"JEEVAN RAHASYA",
"SAMBHOG SE SAMADHI KI AUR",
"SATYA KA DARSHAN",
"VIGYAN DHARAM AUR KALA",
"KYA MANUSHYA EK YANTRA HAI?",
"JYOTISH VIGYAN",
"PANTH PREM KO ATPATO",
"PATH KI KHOJ",
"KARUNA AUR KRANTI",
"SWAYAM KI SATTA",
"PHIR AMRIT KI BUND PARI",
"AMRIT DWAR",
"ANKHO DEKHI SANCH",
"JEEVAN DARSHAN",
"JEEVAN KRANTI KE SUTRA",
"EK NAYA DWAR",
"JEEVAN KI KHOJ",
"GAHRE PANI PAITH",
"KYA ISHWAR MAR GAYA HAI?",
"TAMSO MA JYOTIRGAMAY",
"SATYA KI PYAS",
"CHETI SAKE TO CHET",
"MAN KA DARPAN",
"AMRIT VARSHA",
"MITTI KE DIYE",
"DHYAN KE KAMAL",
"BIN BATI BIN TEL",
"ES DHAMMO SANANTANO VOL 01",
"ES DHAMMO SANANTANO VOL 03",
"ES DHAMMO SANANTANO VOL 04",
"ES DHAMMO SANANTANO VOL 05",
"ES DHAMMO SANANTANO VOL 06",
"ES DHAMMO SANANTANO VOL 07",
"ES DHAMMO SANANTANO VOL 08",
"ES DHAMMO SANANTANO VOL 09",
"ES DHAMMO SANANTANO VOL 10",
"ES DHAMMO SANANTANO VOL 11",
"ES DHAMMO SANANTANO VOL 12",
"ASHTAVAKRA MAHAGITA VOL 1",
"ASHTAVAKRA MAHAGITA VOL 2",
"ASHTAVAKRA MAHAGITA VOL 3",
"ASHTAVAKRA MAHAGITA VOL 4",
"ASHTAVAKRA MAHAGITA VOL 5",
"ASHTAVAKRA MAHAGITA VOL 6",
"ASHTAVAKRA MAHAGITA VOL 7",
"ASHTAVAKRA MAHAGITA VOL 8",
"ASHTAVAKRA MAHAGITA VOL 9",
"Athato Bhakti Jinghysa Vol.01",
"Athato Bhakti Jinghysa Vol.02",
"Bharat Ek Amrit Path",
"Bharat Ke Jalte Prashna",
"Hasiba Khelia Dhariba Dhyanam",
"Mahaveer Vani Vol.01",
"Mahaveer Vani Vol.02",
"Nahi Ram Bin Tao",
"Patanjali Yog Sutra Vol.1",
"Patanjali Yog Sutra Vol.2",
"Patanjali Yog Sutra Vol.3",
"Patanjali Yog Sutra Vol.4",
"Patanjali Yog Sutra Vol.5",
"Tao Upnishad Vol. 1",
"Tao Upnishad Vol. 2",
"Tao Upnishad Vol. 3",
"Tao Upnishad Vol. 4",
"Tao Upnishad Vol. 5",
"Tao Upnishad Vol. 6",
"Bahuri Na Aiso Davn",
"Jo Bolen to Hari Katha",
"Tantra Sutra Vol 1",
"Tantra Sutra Vol. 2 ",
"Tantra Sutra Vol.3",
"Tantra Sutra Vol.4",
"Tantra sutra Vol.5",
"Bin Ghan Parat Phuhar (PB)",
"Lagan Muhurat Jhoot Sab",
"Prem Kya Hai",
"Ami Jharat Bigsat Kanwal",
"Ram Nam Jano Nahi",
"Samund Samana Bund Mein",
"Sansar Aur Marg"];

var subject = ["KRISHNA", 
"MAHAVEER", 
"MAHAVEER", 
"MAHAVEER", 
"MAHAVEER", 
"MAHAVEER", 
"GORAKH", 
"CHARANDAS", 
"SHIV", 
"SARHAPA", 
"NANAK", 
"PALTUVANI", 
"RAIDAS", 
"DARIYADAS", 
"PHARID", 
"KABIR", 
"KABIR", 
"KABIR", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"DHYAN/SADHANA", 
"UPANISHAD", 
"PRASHNOTTAR", 
"DHYAN/SADHANA", 
"MAIBEEL COLLINS", 
"PATRA-SANKALAN", 
"YOG", 
"MEERA", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"VIVIDH", 
"BODH KATHA", 
"SADHANA SHIVIR", 
"UPANISHAD", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"BUDHHA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"ASHTAVAKRA", 
"Shandilya", 
"Shandilya", 
"NA", 
"Rajneeti & Shiksha", 
"NA", 
"Mahaveer", 
"Mahaveer", 
"Prashnottar", 
"Yog", 
"Yog", 
"Yog", 
"Yog", 
"Yog", 
"Tao", 
"Tao", 
"Tao", 
"Tao", 
"Tao", 
"Tao", 
"Prashnottar", 
"Prashnottar", 
"Tantra", 
"Tantra", 
"Tantra", 
"Tantra", 
"Tantra", 
"Sahajobai", 
"Prashnottar", 
"Prashnottar", 
"Prashnottar", 
"Prashnottar", 
"Vividh", 
"Tao", 

];  

for (i = 0; i < books.length; i++) {
    $("#book-title" + [i]).append(books[i]);
}
    